"""se incluye columma user

Revision ID: 808a50269650
Revises: 612ae1d87b07
Create Date: 2023-09-23 23:11:58.371582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808a50269650'
down_revision = '612ae1d87b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
